/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "group_create_proc.sql".}} 
{{ template "group_update_proc.sql".}} 
{{ template "group_delete_proc.sql".}} 
{{ template "group_undo_delete_proc.sql".}} 
{{ template "country_create_proc.sql".}} 
{{ template "country_update_proc.sql".}} 
{{ template "country_delete_proc.sql".}} 
{{ template "country_undo_delete_proc.sql".}} 
{{ template "company_create_proc.sql".}} 
{{ template "company_update_proc.sql".}} 
{{ template "company_delete_proc.sql".}} 
{{ template "company_undo_delete_proc.sql".}} 
{{ template "account_create_proc.sql".}} 
{{ template "account_update_proc.sql".}} 
{{ template "account_delete_proc.sql".}} 
{{ template "account_undo_delete_proc.sql".}} 

